config/routes.rb
Rails.application.routes.draw do
	
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts, :profile
  resources :program
  root 'posts#index'
  get 'profile', to: 'profile#index'

  match 'active'  => 'sessions#active',  via: :get
  match 'timeout' => 'sessions#timeout', via: :get
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :category, optional: true

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/program.rb
class Program < ApplicationRecord
	
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :omniauth_providers => [:facebook]


  def self.from_omniauth(auth)
  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  		user.email = auth.info.email
    	user.password = Devise.friendly_token[0,20]
    	user.name = auth.info.name   # assuming the user model has a name
    	# If you are using confirmable and the provider(s) you use validate emails, 
    	# uncomment the line below to skip the confirmation emails.
    	user.skip_confirmation!
	end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?
	auto_session_timeout 1.hour

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address, :pekerjaan, :email, :password])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name, :address, :pekerjaan, :email ,:password])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show]

	def index
		if params[:category].blank?
			@posts = Post.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@posts = Post.where(:category_id => @category_id).order("created_at DESC")
		end
	end

	def show
		
	end

	private

		def find_post
			@post = Post.find(params[:id])
		end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

	def index
		@profile = Profile.all
	end

	def show
		
	end

end

app/controllers/program_controller.rb
class ProgramController < ApplicationController
	before_action :find_program, only: [:show]

	def index
		@program = Program.all.order("created_at DESC")
	end

	def show
		
	end

	private

		def find_program
			@program = Program.find(params[:id])
		end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

	def facebook
		@user = User.from_omniauth(request.env["omniauth.auth"])

    	if @user.persisted?
      		sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      		set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    	else
     		session["devise.facebook_data"] = request.env["omniauth.auth"]
      		redirect_to new_user_registration_url
    	end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/program_helper.rb
module ProgramHelper
end

app/views/admin/balekreatif/index.html.erb
<% content_for(:title, "Bale Kreatif Admin") %>

<%= render layout: "layout", locals: { wrapper: true, sidebar: false, hide_breadcrumbs: false } do %>
  <h1>Welcome Bale Kreatif Admin</h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BaleKreatif</title>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'b.png' %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>
  <%= render 'partial/navbar' %>
  <% if controller.controller_name == "posts" && controller.action_name == "index" %>
  <%= render 'partial/banner' %>
  <h3><b><center>KABAR BERITA</center></b></h3>
  <% end %>
  <%= render 'partial/fab' %>

  <% if current_user %>
  <%= auto_session_timeout_js %>
  <% end %>
  
  <div class="">
    <%= render 'partial/message' %>
    <%= yield %>
  </div>

  <%= render 'partial/footer' %>
</body>

<script type="script/javascripts">
  $(".button-collapse").sideNav();
  $( document ).ready(function)
  $(".dropdown-button").dropdown();
  $('.dropdown-button').dropdown('open');
  $(document).ready(function() {
    $('select').material_select();
  });
  $(document).ready(function(){
    $('.slider').slider();
  });
</script>
</html>

app/views/partial/_banner.html.erb
<!-- <main>
	<div id="index-banner" class="section no-pad-bot blue darken-1">
		<div class="container">
			<br>
			<br>
			<h1 class="header center white-text">
				Welcome Bale Kreatif
			</h1>
			<div class="row center white-text" >
				<h5 class="header col s12 light">
					"Bale Kreatif suatu komunitas yang di bentuk untuk mengembangkan kreatifitas. komunitas kami memiliki bidang pendidikan, Sosial, Keagamaan dan Ekonomi."
					Berkarya dan Berbagi
				</h5>
				<h6 class="header col s12 light">
					<i class="material-icons">location_city</i>Jl Siliwangi Gg Jayaniti Kota Sukabumi</br>
					<i class="material-icons">email</i>timbalekreatif@gmail.com </br>
					<i class="material-icons">filter_drama</i>Bale Kreatif
				</h6>
			</div>
			<div class="row center">
				<a href="#" class="btn-large waves-effect waves-light pink darken-1"><i class="material-icons left">account_balance_wallet</i>Klik Untuk Donasi</a>
			</div>
			</br>
		</div>
	</div>
</main> -->
<section class="banner">
	<div class="overlay"></div>
	<div class="banner__information">
		<div class="title">
			<span>Welcome Bale Kreatif</span>
		</div>
		<div class="description">
			<p>
				Bale Kreatif suatu komunitas yang di bentuk untuk mengembangkan kreatifitas. komunitas kami memiliki bidang pendidikan, Sosial, Keagamaan dan Ekonomi Berkarya dan Berbagi.
			</p>
		</div>
		<br>
		<a href="#" class="btn-large waves-effect waves-light pink darken-1">
			<i class="material-icons left">
				account_balance_wallet
			</i>
			Klik Untuk Donasi
		</a>
	</div>
</section>

app/views/partial/_dropdown.html.erb
<ul id="dropdown1" class="dropdown-content hover">
  <li><%= link_to 'Home', root_path%></li>
  <li><%= link_to 'Profile', profile_index_path%></li>
</ul>

<ul id="dropdown2" class="dropdown-content hover">
  <li><a href="#!">Pendidikan</a></li>
  <li><a href="#!">Sosial</a></li>
  <li><a href="#!">Keagamaan</a></li>
  <li><a href="#!">Ekonomi</a></li>
</ul>

<ul id="dropdown3" class="dropdown-content hover">
  <li><a href="#!">Dokumentasi Foto</a></li>
</ul>

<ul id="dropdown4" class="dropdown-content hover">
  <% Category.all.each do |c| %>
  <li>
  	<%= link_to c.name, posts_path(category: c.name), class: "link" %>
  </li>
  <% end %>
</ul>

<ul id="dropdown5" class="dropdown-content hover"> 
  <li><%= link_to "Profile Saya", edit_user_registration_path %></li>
  <li><%= link_to "Ubah Password", edit_user_password_path %></li>
  <li><%= link_to "Keluar", destroy_user_session_path, method: :delete, data: { confirm: "Apakah Kamu Yakin Ingin Keluar?" } %></li>
</ul>

app/views/partial/_fab.html.erb
  <div class="fixed-action-btn toolbar">
    <a class="btn-floating btn-large pink darken-1">
      <i class="large material-icons">view_headline</i>
    </a>
    <ul>
      <li class="waves-effect waves-light"><a href="#!"><i class="material-icons">chat_bubble</i></a></li>
      <li class="waves-effect waves-light"><a href="#!"><i class="material-icons">call</i></a></li>
      <li class="waves-effect waves-light"><a href="#!"><i class="material-icons">account_balance_wallet</i></a></li>
      <li class="waves-effect waves-light"><a href="#!"><i class="material-icons">photo_library</i></a></li>
    </ul>
  </div>

app/views/partial/_footer.html.erb
<footer class="page-footer blue">
  <div>
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Bale Kreatif</h5> 
        <h6 class="header grey-text text-lighten-3">
          <i class="material-icons">location_city</i>Jl Siliwangi Gg Jayaniti Kota Sukabumi</br>
          <i class="material-icons">email</i>timbalekreatif@gmail.com </br>
          <i class="material-icons">filter_drama</i>Bale Kreatif
        </h6>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Social</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Google</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Instagram</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div>
      © 2018 Bale Kreatif by Indra Gunawan
    </div>
  </div>
</footer>

app/views/partial/_form.html.erb
<body class="white">
	<main style="padding-top: 1rem">
		<section id="login">
			<div class="container-fluid pt-4">
				<div class="row">
					<div class="col s12 offset-s-1">
						<div class="login-form">
							<div class="card hoverable">
								<div class="card-content">
									<span class="card-title center"><h3><b>Posting Berita Baru</b></h3></span>
									<div class="divider"></div></br>

									<%= simple_form_for @post, :html => { :multipart => true } do |p| %>

									<div class="form-input row">
										<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
										<br>
										<br>
										<div class="input-field">
											<%= p.input :title, autofocus: true %>
										</div>
										<div class="textarea">
											<%= p.input :description %>
										</div>
										<div class="input-field">
											<%= p.input :author %>
										</div>
										<div class="actions center">
											<%= p.button :submit, class: "btn waves-effect waves-light pink darken-1" %>
										</div>
										<% end %>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</main>
</body>

app/views/partial/_message.html.erb
<% unless flash.empty? %>
	<script>
		<% flash.each do |f| %>
		    <% type = f[0].gsub('notice', 'info').gsub('alert', 'error') %>
		    toastr['<%= type %>']('<%= f[1] %>');
		<% end %>
	</script>
<% end %>

app/views/partial/_message_devise.html.erb
<% unless resource.errors.empty? %>
	<script>
		<% resource.errors.full_messages.each do |msg| %>
		    toastr['error']('<%= msg %>');
		<% end %>
	</script>
<% end %>

app/views/partial/_navbar.html.erb
<header class="navbar-fixed">  
  <nav class=" blue darken-1">
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo"><i class="material-icons">cloud</i>Bale <b>Kreatif</b></a>
    </a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><a class="site-nav__link dropdown-button" data-activates="dropdown1" data-beloworigin="true" data-constrainwidth="false" data-hover="true"><i class="material-icons left">home</i>Home</a></li>
      <li><a class="site-nav__link dropdown-button" data-activates="dropdown3" data-beloworigin="true" data-constrainwidth="false" data-hover="true"><i class="material-icons left">collections</i>Galeri</a></li>
            <li><%= link_to "Program Dan Kegiatan", program_index_path %></li>
      <% if !user_signed_in? %>
        <li><%= link_to "Masuk", new_user_session_path %></li>
        <li><%= link_to "Daftar", new_user_registration_path, class: "btn waves-effect waves-light pink darken-1" %></li>
      <% else %>
        <li><a class="site-nav__link dropdown-button" data-activates="dropdown5" data-beloworigin="true" data-constrainwidth="false" data-hover="true"><i class="material-icons left">person_pin</i><%= current_user.name%></a></li>
      <% end %>
    </ul>
  </div>
</nav>
</header>

<%= render 'partial/dropdown' %>

app/views/partial/_promotion.html.erb
<div class="row grey lighten-3">
  <div class="col s4">
    <div class="center promo promo-example">
      <div class="col s12">
        <%= image_tag("muraz.jpg", class: 'responsive-img') %>
      </div>
      <a class="grey-text text-brown lighten-3"><p class="promo-caption">Apa Kata Mereka Tentang Bale Kreatif</p></a>
      <a class="grey-text text-brown lighten-3"><p class="light center">
        We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components.
        We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components.
        We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components.
      </p></a>
      <h6 class="grey-text text-brown lighten-3">"Moch Muraz (Walikota Sukabumi)"</h6>
    </div>
  </div>
  <div class="col s4">
    <div class="center promo promo-example">
      <div class="col s12">
        <%= image_tag("marwan.jpg", class: 'responsive-img') %>
      </div>
      <a class="grey-text text-brown lighten-3"><p class="promo-caption">Apa Kata Mereka Tentang Bale Kreatif</p></a>
      <a class="grey-text text-brown lighten-3"><p class="light center">
        By utilizing elements and principles of Material Design, we were able to create a framework that focuses on User Experience.
        By utilizing elements and principles of Material Design, we were able to create a framework that focuses on User Experience.
        By utilizing elements and principles of Material Design, we were able to create a framework that focuses on User Experience.
      </p></a>
      <h6 class="grey-text text-brown lighten-3">"Marwan Hamami (Bupati Sukabumi)"</h6>
    </div>
  </div>
  <div class="col s4">
    <div class="center promo promo-example">
      <div class="col s12">
        <%= image_tag("ahmad heryawan.jpg", class: 'responsive-img') %>
      </div>
      <a class="grey-text text-brown lighten-3"><p class="promo-caption">Apa Kata Mereka Tentang Bale Kreatif</p></a>
      <a class="grey-text text-brown lighten-3"><p class="light center">
        We have provided detailed documentation as well as specific code examples to help new users get started.We have provided detailed documentation as well as specific code examples to help new users get started.We have provided detailed documentation as well as specific code examples to help new users get started.
      </p></a>
      <h6 class="grey-text text-brown lighten-3">"Ahmad Heryawan, Lc (Gubernur Jawa Barat)"</h6>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<h1 class="current-category center"><%= params[:category] %></h1>

<% if @posts.count == 0 %>
<div>
	<h4 class="center-align">"Kategori Berita Yang Anda Pilih Saat Ini Tidak Tersedia"</h4>
</div>
<% else %>
<div class="row">
	<% @posts.each do |p| %>
	<%= link_to p do %>
	<div class="col s6 m3">
		<div class="card small">
			<div class="card-image waves-effect waves-block waves-light">
				<%= image_tag p.image.url %>
			</div>
			<div class="card-content">
				<span class="card-title grey-title text-darken-4">
					<h6><b><%= p.title %></b></h6>
					<h6 class="black-text">Oleh: <%= p.author %></h6>
					<h6 class="black-text"><%= I18n.l(p.created_at.to_date) %></h6>
				</span>
			</div>
		</div>
	</div>
	<% end %>
	<% end %>
	<% end %>
</div>

<%= render 'partial/promotion' %>

app/views/posts/show.html.erb
<div class="container">
	<center><%= image_tag @post.image.url, class: 'card large' %></center>
	<h3><%= @post.title %></h3>
	<p><b><%= @post.created_at.strftime("%A, %d %B %Y %H:%M:%S") %></b></p>
	<h5>Penulis: <%= @post.author %></h5>
	<p><%= @post.description %></p>
	<%= link_to "Back", root_path %>
</div>

app/views/program/index.html.erb
<div class="row">
	<% @program.each do |p| %>
	<%= link_to p do %>
	<div class="col s6 m3">
		<div class="card small">
			<div class="card-image waves-effect waves-block waves-light">
				<%= image_tag p.image.url %>
			</div>
			<div class="card-content">
				<span class="card-title grey-title text-darken-4">
					<h6><b><%= p.title %></b></h6>
					<h6 class="black-text"><%= p.author %></h6>
					<h6 class="black-text"><%= I18n.l(p.created_at.to_date)%></h6>
				</span>	
			</div>
		</div>
	</div>
	<% end %>
	<% end %>
</div>

app/views/program/show.html.erb
<h1>Show Data</h1>